const dadJokes = [
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I would avoid the sushi if I was you. It’s a little fishy.",
  "Want to hear a joke about construction? I’m still working on it.",
  "I used to play piano by ear, but now I use my hands.",
  "Did you hear about the Italian chef that died? He pasta way.",
  "I’m reading a book on anti-gravity. It’s impossible to put down!",
  "Want to hear a joke about a piece of paper? Never mind, it’s tearable.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "How does a penguin build its house? Igloos it together.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "I wouldn’t buy anything with velcro. It’s a total rip-off.",
  "I made a pencil with two erasers. It was pointless.",
  "I asked my dog what’s two minus two. He said nothing.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "Why couldn’t the bicycle stand up by itself? It was two tired.",
  "What’s brown and sticky? A stick.",
  "Why can’t you give Elsa a balloon? Because she will let it go.",
  "How does a taco say grace? Lettuce pray.",
  "Want to hear a joke about a piece of paper? Never mind... it’s tearable.",
  "Why did the math book look sad? Because it had too many problems.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Did you hear about the kidnapping at the playground? They woke up.",
  "How do you organize a space party? You planet.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "I only know 25 letters of the alphabet. I don’t know Y.",
  "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
  "What do you call fake spaghetti? An impasta!",
  "How does a vampire start a letter? Tomb it may concern...",
  "How do you make a tissue dance? You put a little boogie in it.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "I used to have a job as a professional cricket player, but I quit. It just wasn’t my bat.",
  "Why was the big cat disqualified from the race? Because it was a cheetah.",
  "What did the fish say when it hit the wall? Dam!",
  "What did one hat say to the other? You stay here; I’ll go on ahead.",
  "Why do cows have hooves instead of feet? Because they lactose.",
  "Did you hear about the fire at the circus? It was in tents!",
  "What do you call a man with no nose and no body? Nobody nose.",
  "Why did the banana go to the doctor? Because it wasn’t peeling well.",
  "What’s a skeleton’s least favorite room in the house? The living room.",
  "I told my wife she was drawing her eyebrows too high. She seemed surprised.",
  "What time did the man go to the dentist? Tooth-hurty.",
  "I used to be a baker, but I couldn’t make enough dough.",
  "What’s brown and sounds like a bell? Dung!",
  "Why don’t they play poker in the jungle? Too many cheetahs.",
  "I used to be addicted to the hokey pokey, but I turned myself around.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "What’s the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle? Attire.",
  "Why do melons have weddings? Because they cantaloupe.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "What did the big flower say to the little flower? Hi, bud!",
  "Why couldn’t the lifeguard save the hippie? Because he was too far out, man.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why can’t a nose be 12 inches long? Because then it would be a foot.",
  "How do you organize a space party? You planet.",
  "Why are skeletons so calm? Because nothing gets under their skin.",
  "I would tell you a chemistry joke, but I know I wouldn’t get a reaction.",
  "What’s green and has wheels? Grass. I lied about the wheels.",
  "I just watched a documentary about beavers. It was the best dam show I ever saw!",
  "Why did the math book look sad? Because it had so many problems.",
  "Did you hear about the circus fire? It was in tents!",
  "Why can’t you hear a pterodactyl go to the bathroom? Because the “P” is silent.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "How does a penguin build its house? Igloos it together.",
  "I used to be a baker, but I couldn’t make enough dough.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "How do you find Will Smith in the snow? You look for fresh prints.",
  "Why don’t oysters donate to charity? Because they are shellfish.",
  "How does a taco say grace? Lettuce pray.",
  "I have a few jokes about unemployed people, but none of them work.",
  "What’s blue and not very heavy? Light blue.",
  "I couldn’t figure out how the seatbelt worked. Then it just clicked.",
  "Why did the belt get arrested? For holding up a pair of pants.",
  "Why did the coffee file a police report? It got mugged.",
  "I used to work in a shoe recycling shop. It was sole-destroying.",
  "Why did the computer go to the doctor? Because it had a virus.",
  "How do trees access the internet? They log in.",
  "What did the grape do when it got stepped on? Nothing but let out a little wine.",
  "Why don’t cows have any money? Because farmers milk them dry.",
  "What does a bee use to brush its hair? A honeycomb.",
  "Why was the broom late? It swept in.",
  "Did you hear about the light bulb party? It was pretty lit.",
  "What kind of music do mummies listen to? Wrap music.",
  "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
  "What do you call a fish with no eyes? Fsh.",
  "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
  "What did the pirate say on his 80th birthday? Aye matey!",
  "What did the zero say to the eight? Nice belt!",
  "Why did the cookie go to the hospital? Because it felt crumby.",
  "I have a joke about pizza, but it’s too cheesy.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "How does a dog stop a video? It presses paws.",
  "Why are ghosts such bad liars? Because they are too transparent.",
  "How do you make holy water? You boil the hell out of it.",
  "What did one ocean say to the other? Nothing, they just waved.",
];

const btn = document.querySelector(".btn");
function generate() {
  let randdomn = Math.floor(Math.random() * dadJokes.length);
  const joke = dadJokes[randdomn];
//   console.log(joke);
  const JokeOutPut = document.querySelector(".output");
  JokeOutPut.textContent = `"${joke}🤣😂"`;
}

btn.addEventListener("click", generate);
